<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;netstandard2.0</TargetFrameworks>
    <LangVersion>13.0</LangVersion>
    <DebugType>embedded</DebugType>
    <Nullable>enable</Nullable>
    
    <PackageId>DigOrDie.DODModAPI.AssetPacker</PackageId>
    <AssemblyName>DODModAPI.AssetPacker</AssemblyName>
    <Version>0.1.1</Version>
    <Authors>ddmitv</Authors>
    <Description>MSBuild task for generating C# bindings and optimized sprite atlases for DODModAPI</Description>
    <PackageTags>DigOrDie;Modding;GameModding;MSBuild</PackageTags>
    <RepositoryUrl>https://github.com/ddmitv/dig-or-die-mods</RepositoryUrl>
    <RepositoryType>git</RepositoryType>

    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <RootNamespace>DODModAPI.AssetPacker</RootNamespace>

    <BuildOutputTargetFolder>tasks</BuildOutputTargetFolder>
    <DevelopmentDependency>true</DevelopmentDependency>
    <NoPackageAnalysis>true</NoPackageAnalysis>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="18.4.0" PrivateAssets="all" />
    <PackageReference Include="SixLabors.ImageSharp" Version="2.1.13" PrivateAssets="all" />
    <PackageReference Include="PolySharp" Version="1.15.0" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers" />
  </ItemGroup>

  <ItemGroup>
    <None Include="build/*" PackagePath="build/" Pack="true" />
  </ItemGroup>

  <Target Name="PackTaskDependencies" BeforeTargets="GenerateNuspec">
    <ItemGroup>
      <_PackageFiles Include="bin\$(Configuration)\*\SixLabors.ImageSharp.dll" PackagePath="tasks%(RecursiveDir)" Visible="false" BuildAction="Content" />
    </ItemGroup>
  </Target>
</Project>