<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Plugin.Common.props" />

  <PropertyGroup>
    <AssemblyName>debug_mode</AssemblyName>
    <Product>Debug Mode</Product>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../dodmodapi/dodmodapi.csproj" Private="false" />
  </ItemGroup>

  <Import Project="../Plugin.Common.targets" />
</Project>
