<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Plugin.Common.props" />

  <PropertyGroup>
    <AssemblyName>dodmodapi</AssemblyName>
    <Product>DODModAPI</Product>
    <PackageId>DigOrDie.DODModAPI</PackageId>
    <RootNamespace>DODModAPI</RootNamespace>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AssetPacker/**;example-mod/**" />
    <None Remove="AssetPacker/**;example-mod/**" />
  </ItemGroup>
  <Import Project="../Plugin.Common.targets" />
</Project>
