<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Plugin.Common.props" />

  <PropertyGroup>
    <AssemblyName>more_items</AssemblyName>
    <Product>More Items</Product>
    <Version>1.2.0</Version>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="../dodmodapi/dodmodapi.csproj" Private="false" />
    <PackageReference Include="DigOrDie.DODModAPI.AssetPacker" Version="0.1.0-re.*" />
  </ItemGroup>

  <ItemGroup>
    <ModSprites Include="textures/sprites.cfg" AtlasName="Textures" />
  </ItemGroup>
  
  <Import Project="../Plugin.Common.targets" />
</Project>
 