<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Plugin.Common.props" />

  <PropertyGroup>
    <AssemblyName>dedicated_client</AssemblyName>
    <Product>Dedicated Client</Product>
    <Version>1.0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../dodmodapi/dodmodapi.csproj" Private="false" />
  </ItemGroup>
  
  <Import Project="../Plugin.Common.targets" />
</Project>
