name: Github Pages

on:
  push:
    branches:
      - main
    paths:
      - 'tools/world-viewer/**'
      - '.github/workflows/gh-pages.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-github-pages:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Rust toolchain for wasm
        run: |
          rustup update stable
          rustup default stable
          rustup set profile minimal
          rustup target add wasm32-unknown-unknown
        working-directory: ./tools/world-viewer
          
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "tools/world-viewer -> target"

      - name: Download and install Trunk binary
        run: wget -qO- https://github.com/thedodd/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
        working-directory: ./tools/world-viewer

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v6

      - name: Build
        run: ./trunk build --release --public-url "${{ steps.pages.outputs.base_path }}/"
        working-directory: ./tools/world-viewer
        env:
          RUSTFLAGS: -D warnings

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./tools/world-viewer/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5